export enum SplashActionType {
  SET_LOADING = "SET_LOADING",
  SET_NO_INTERNET = "SET_NO_INTERNET",
  SET_FORCE_UPDATE_REQUIRED = "SET_FORCE_UPDATE_REQUIRED",
  SET_HOME = "SET_HOME",
  SET_SERVER_ERROR = "SET_SERVER_ERROR",
  SET_FORMAT_VERSION_ERROR = "SET_FORMAT_VERSION_ERROR",
  SET_UNKNOWN_ERROR = "SET_UNKNOWN_ERROR" 
}
