export enum NextScreenToSplash {
    NO_INTERNET = 'NO_INTERNET',
    FORCE_UPDATE = 'FORCE_UPDATE',
    HOME = 'HOME',
    SERVER_ERROR = 'SERVER_ERROR',
    FORMAT_VERSION_ERROR = 'FORMAT_VERSION_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR' 
}
